ioet/time-tracker-backend

- README.md
- time_tracker_api/__init__.py
- time_tracker_api/activities/activities_api.py
- time_tracker_api/api.py
- time_tracker_api/projects/projects_api.py
This PR creates an API definition to manage activities.
> Create api definition activies#4

- time_tracker_api/activities/activities_api.py
- time_tracker_api/api.py
- time_tracker_api/time_entries/time_entry_api.py
Creates the API definition for Time Entries, which are those created every time a user starts a new activity.
> Create API definition for time entries

- .gitignore
- README.md
- cli.py
- requirements/prod.txt
- run.py
This PR makes possible to run CLI commands:
- gen_swagger_json: Exports swagger specifications in JSON format, namely swagger.json
- gen_postman_collection: Generates a Postman Collection for the API
Check out the README for better information.
> Add CLI commands to generate API definition

- time_tracker_api/activities/activities_api.py
- time_tracker_api/api.py
- time_tracker_api/projects/projects_api.py
- time_tracker_api/technologies/technologies_api.py
- time_tracker_api/time_entries/time_entry_api.py
We define a model structure for each model, which contains fields. Some of those fields are shared for almost all models. Those fields are specifically for auditing the  model (e.g. `created_at`, `created_by`, `tenant_id`). This PR created a common structure for those fields and reuse it across several models.
> Fixes #18 - create common structure and use it across models

- .gitignore
- README.md
- cli.py
- requirements/dev.txt
- setup.cfg
- setup.py
- tests/conftest.py
- tests/projects/projects_namespace_test.py
- tests/smoke_test.py
- time_tracker_api/projects/projects_namespace.py
This PR adds **pytest** and **coverage**, in order to run tests and coverage reports respectively. It also adds a sample smoke_test.py to very that the tests are well installed by checking that the a reference to the app can be accessed. For better comprehension, more instructions were added to the README.md.
> Fixes #17 Add tests and coverage support

- .env.template
- .gitignore
- README.md
- run.py
- tests/conftest.py
- tests/projects/projects_namespace_test.py
- time_tracker_api/__init__.py
- time_tracker_api/api.py
- time_tracker_api/config.py
- time_tracker_api/database.py
- time_tracker_api/projects/projects_model.py
- time_tracker_api/projects/projects_namespace.py
- time_tracker_api/sql_repository.py
This PR:
- Fixes the issue related to the random lose of data
- Test persistence of the API namespace for projects
This will set the foundation for future tests of the persistence of API namespaces, covering 100% of it.
> Persist and test API namespace for projects

- README.md
- requirements/prod.txt
- tests/projects/projects_namespace_test.py
- tests/resources.py
- tests/smoke_test.py
- tests/time_entries/time_entries_namespace_test.py
- time_tracker_api/activities/activities_model.py
- time_tracker_api/activities/activities_namespace.py
- time_tracker_api/api.py
- time_tracker_api/config.py
- time_tracker_api/database.py
- time_tracker_api/projects/projects_model.py
- time_tracker_api/projects/projects_namespace.py
- time_tracker_api/sql_repository.py
- time_tracker_api/time_entries/time_entries_model.py
- time_tracker_api/time_entries/time_entries_namespace.py
This PR:
- Creates the implementation for the API namespace for time entries
- Creates the tests for the API namespace for time entries
- Replaces the status codes for constants
- Improves documentation of expected status codes for the API namespace for projects and time entries
> Implementation and test of api namespaces for time entries #13

- tests/activities/activities_namespace_test.py
- time_tracker_api/activities/activities_model.py
- time_tracker_api/activities/activities_namespace.py
This PR includes :
- Implementation for the Activity Model
- Suite of test for the Activity Model
I reused most of the implementation of projects. Thanks @EliuX for your help on it.
> Implement activities model

- requirements/dev.txt
- requirements/prod.txt
- tests/smoke_test.py
- time_tracker_api/config.py
It fixes the user of env variables in Azure. In addition, having into account that all variables we set are gotten in Python as strings, e.g. `True` we need to set a convention to what is a Truthy or a falsy value. So I decided to basically allow to specify some falsy discrete values, which are:
- `false`
- `0`
- `disabled`
Any different string to those ones (case-insensitive) will be considered as True. These values will be contained in the constant `time_tracker_api.config.DISABLE_STR_VALUES`.
> Solve #46 by using standard naming of env vars 

- requirements/prod.txt
- setup.py
- time_tracker_api/__init__.py
- time_tracker_api/config.py
This PR is meant to Enable CORS (#54) but also renames the main project from time-tracker-api to time-tracker-backend.
> Enable CORS

- time_tracker_api/api.py
- time_tracker_api/customers/customers_model.py
- time_tracker_api/customers/customers_namespace.py
- time_tracker_api/project_types/project_types_model.py
- time_tracker_api/project_types/project_types_namespace.py
> Add project type and customer models

- Dockerfile
- README.md
- requirements/time_tracker_api/prod.txt
- setup.cfg
- time_tracker_api/__init__.py
- time_tracker_api/api.py
This PR contains the following changes:
- Add the library python-semantic-release for automatic versioning.
- Add instructions to make automatic releases.
- Update version of app.
- Use the commit message style in commits to later test automatic versioning & release.
> Add semantic versioning

- .env.template
- .gitignore
- README.md
- commons/data_access_layer/cosmos_db.py
- migrations/01-initialize-db.py
- migrations/__init__.py
- requirements/migrations.txt
- tests/commons/data_access_layer/cosmos_db_test.py
- tests/conftest.py
- time_tracker_api/activities/activities_model.py
- time_tracker_api/config.py
- time_tracker_api/customers/customers_model.py
- time_tracker_api/project_types/project_types_model.py
- time_tracker_api/projects/projects_model.py
- time_tracker_api/projects/projects_namespace.py
- time_tracker_api/time_entries/time_entries_model.py
In this PR it is installed and configured a library to run migrations. In addition, it creates an initial migration that creates an initial database schema. With containers for:
- Project
- Project type
- Activity
- Customer
- Time entry
Although the library for migrations we are using [is not perfect](https://github.com/Lieturd/migrate-anything/issues/3), we were able to run the migrations and persist them in Azure Cosmos DB.
> Closes #36 Allow to run migrations

- .env.template
- commons/data_access_layer/cosmos_db.py
- tests/commons/data_access_layer/cosmos_db_test.py
- tests/conftest.py
- tests/time_tracker_api/time_entries/time_entries_model_test.py
- tests/time_tracker_api/time_entries/time_entries_namespace_test.py
- time_tracker_api/activities/activities_model.py
- time_tracker_api/activities/activities_namespace.py
- time_tracker_api/api.py
- time_tracker_api/customers/customers_model.py
- time_tracker_api/customers/customers_namespace.py
- time_tracker_api/project_types/project_types_model.py
- time_tracker_api/project_types/project_types_namespace.py
- time_tracker_api/projects/projects_model.py
- time_tracker_api/projects/projects_namespace.py
- time_tracker_api/time_entries/time_entries_model.py
- time_tracker_api/time_entries/time_entries_namespace.py
In this PR we make possible change the model of the time entries, so that it is checked that the current user can only manipulate time entry items where he is the owner, otherwise he will get an 403 error:
This is possible because of the new parameter `peeker` and `conditions`:
* peeker: It is a peeker that is meant to watch the item that is manipulated and if a biz-logic criteria requirement is not fulfilled it can short-circuit the user request flow by raising an `CustomError`.
* conditions: It is a python dictionary that contains the attribute and the corresponding expected value we expect the entries have in the database. This is done by creating an equality condition in the where clause of the SQL query executed in the function `find_all`.
> fix: Close #82 Enforce users manipulate only their time entries

- time_tracker_api/__init__.py
> Serve swagger.json on UI over https

- commons/data_access_layer/database.py
- commons/data_access_layer/sql.py
- requirements/time_tracker_api/prod.txt
- tests/commons/data_access_layer/sql_test.py
- tests/conftest.py
- tests/time_tracker_api/activities/activities_namespace_test.py
- tests/time_tracker_api/customers/customers_namespace_test.py
- tests/time_tracker_api/project_types/project_types_namespace_test.py
- tests/time_tracker_api/projects/projects_namespace_test.py
- tests/time_tracker_api/security_test.py
- tests/time_tracker_api/time_entries/time_entries_namespace_test.py
- time_tracker_api/api.py
- time_tracker_api/config.py
- time_tracker_api/security.py
- time_tracker_api/time_entries/time_entries_model.py
In this PR we are requiring authenticated users using JWT. To do so, we are using the library [PyJWT](https://pypi.org/project/PyJWT/), so in every request to the API we expect a header `Authorization` with a format like 
>Bearer <JWT>
In the Swagger UI, you will now see a new button called "Authorize":
when you click it then you will be notified that you must enter the content of the Authorization header, as mentioned before:
Click "Authorize" and then close that dialog. From that moment forward you will not have to do it anymore because the Swagger UI will use that JWT in every call, e.g.
If you want to check out the data (claims) that your JWT contains, you can also use the CLI of [PyJWT](https://pypi.org/project/PyJWT/):
```
pyjwt decode --no-verify "<JWT>"
```
Remember that the API …
> Close #94 Enforce authentication by JWT

- .pre-commit-config.yaml
- README.md
- commons/git_hooks/enforce_semantic_commit_msg.py
- requirements/time_tracker_api/dev.txt
> Feature/enforce commit message style#78

- commons/data_access_layer/cosmos_db.py
- tests/conftest.py
- tests/time_tracker_api/time_entries/time_entries_model_test.py
- time_tracker_api/time_entries/time_entries_model.py
- time_tracker_api/time_entries/time_entries_namespace.py
In this PR we set the `start_date` of the time entries to **not required**. Therefore, the value of it will be auto-generated to the current UTC date.
> Close #96 Autogenerate start_date if not present

- README.md
- commons/data_access_layer/cosmos_db.py
- tests/commons/data_access_layer/cosmos_db_test.py
- tests/commons/data_access_layer/sql_test.py
- tests/conftest.py
- tests/time_tracker_api/security_test.py
- tests/time_tracker_api/time_entries/time_entries_model_test.py
- tests/time_tracker_api/time_entries/time_entries_namespace_test.py
- time_tracker_api/security.py
- time_tracker_api/time_entries/time_entries_model.py
This does multiple things:
- It starts allowing any subdomain of in b2clogin.com in the claim `iss` of the JWT the API requires.
- In the running endpoint, it filters the running endpoint by the owner_id.
- It verifies through a test that the string representations of the UTC `datetime` entries, e.g. the `start_date` and `end_date` in the time entries, can be compared effectively.
- Adds documentation in the README about how to use the JWT to authenticate.
> Close #103 Filter running time entry by owner_id

- commons/data_access_layer/cosmos_db.py
- commons/data_access_layer/database.py
- tests/conftest.py
- tests/time_tracker_api/activities/activities_namespace_test.py
- tests/time_tracker_api/api_test.py
- time_tracker_api/__init__.py
- time_tracker_api/api.py
- time_tracker_api/project_types/project_types_namespace.py
- time_tracker_api/projects/projects_namespace.py
- time_tracker_api/security.py
- time_tracker_api/time_entries/time_entries_model.py
- time_tracker_api/time_entries/time_entries_namespace.py
fix: #91 adding filter by attributes
> fix: #91 adding filter by attributes

- commons/data_access_layer/cosmos_db.py
- tests/commons/data_access_layer/cosmos_db_test.py
- tests/time_tracker_api/project_types/project_types_namespace_test.py
- tests/time_tracker_api/time_entries/time_entries_namespace_test.py
- time_tracker_api/activities/activities_namespace.py
- time_tracker_api/api.py
- time_tracker_api/customers/customers_namespace.py
- time_tracker_api/project_types/project_types_namespace.py
- time_tracker_api/projects/projects_namespace.py
- time_tracker_api/time_entries/time_entries_model.py
- time_tracker_api/time_entries/time_entries_namespace.py
This PR allows deleting optional ids by specifying `null` as value. Before that, this was not possible because a string was expected.
In addition, based on a request made by @enriquezrene , I allowed the `UUID` fields to match an empty string and before saving I matched in the `on_create` and `on_update` methods of the Cosmos DB repository whether an attribute was an empty text. If so, that value would be replaced by a `null` value.
> Close #107 Allow removing id by specifying null

- tests/time_tracker_api/api_test.py
- time_tracker_api/__init__.py
- time_tracker_api/activities/activities_namespace.py
- time_tracker_api/api.py
- time_tracker_api/customers/customers_namespace.py
- time_tracker_api/project_types/project_types_namespace.py
- time_tracker_api/projects/projects_namespace.py
- time_tracker_api/time_entries/time_entries_namespace.py
In this PR we solve the following issues:
- Set the field URI of time entries to nullable, as specified in #111 
- Allow ignoring required fields while updating an item. As requested in #112
> Fix issues required with model fields

- time_tracker_api/activities/activities_namespace.py
- time_tracker_api/customers/customers_namespace.py
- time_tracker_api/project_types/project_types_namespace.py
- time_tracker_api/projects/projects_namespace.py
- time_tracker_api/time_entries/time_entries_namespace.py
fix: #114 description should be optional on time-entry creation
> fix: #114 description should be optional

- commons/data_access_layer/cosmos_db.py
- commons/data_access_layer/database.py
- migrations/__init__.py
- tests/commons/data_access_layer/cosmos_db_test.py
- tests/conftest.py
- tests/time_tracker_api/time_entries/time_entries_model_test.py
> Fix: update migration scripts to work with the events implementation

- commons/data_access_layer/cosmos_db.py
- time_tracker_api/config.py
- time_tracker_api/time_entries/time_entries_model.py
- time_tracker_api/time_entries/time_entries_namespace.py
Fixes #126 
Most of changes is autoformatting code with `black` library. The actual fix is 
```
data['owner_id'] = event_ctx.user_id
```
As mentioned in #126
> Fix/find running after create time entry not working#126

- README.md
- tests/time_tracker_api/projects/projects_namespace_test.py
- time_tracker_api/projects/projects_model.py
- time_tracker_api/projects/projects_namespace.py
This PR adds  new field named technologies to the `/projects` resource.
Now the request may look like this:
```
{
"tenant_id": "cc925a5d-9644-4a4f-8d99-xxxxxxxxxx",
"name": "Project 6",
"description": "Test project",
"customer_id": "e2849284-8283-4561-ad04-87065624db8b",
"project_type_id": null,
"technologies": [
"python",
"react"
]
}
```
> Feature 125/add technologies to project

- commons/data_access_layer/cosmos_db.py
- tests/time_tracker_api/time_entries/time_entries_namespace_test.py
- time_tracker_api/time_entries/custom_modules/worked_time.py
- time_tracker_api/time_entries/time_entries_model.py
- time_tracker_api/time_entries/time_entries_namespace.py
Close #108 
I get time entries from start of month and current datetime, from the  DB, and then apply logic to it. 
Such logic is inside the module `worked_time`,  a custom module inside the time_entries namespace.
In `tests/time_tracker_api/time_entries/time_entries_namespace_test.py` the actual test is at line 663.
> Feature/computed worked time#108

- commons/data_access_layer/cosmos_db.py
- time_tracker_api/time_entries/custom_modules/worked_time.py
> Fix(summary): set all datetimes explicitly to UTC

- commons/data_access_layer/cosmos_db.py
- time_tracker_api/database.py
- time_tracker_api/projects/projects_model.py
Ticket: https://github.com/orgs/ioet/projects/5#card-37540366
> Don't display projects that belong to deleted customers

- time_tracker_api/time_entries/custom_modules/utils.py
- time_tracker_api/time_entries/time_entries_model.py
- time_tracker_api/time_entries/time_entries_namespace.py
> Feat(time-entries): include project name in time-entries response

- commons/data_access_layer/cosmos_db.py
- time_tracker_api/time_entries/time_entries_model.py
> refactor(type-hints): :recycle: add Callable as type hint of functions

- tests/time_tracker_api/time_entries/time_entries_namespace_test.py
- time_tracker_api/time_entries/time_entries_model.py
The `partial_update` method in repository base class uses the find method. As the method was overridden, this was causing errors. This function should be latter refactored somehow to avoid those issues. By now the best solution is to move the logic of add project names to the TimeEntriesDao instead of doing it in the repository.
Issue related #140
> fix(time-entries): :ambulance: move logic of project names to time-entries DAO

- time_tracker_api/projects/custom_modules/utils.py
- time_tracker_api/projects/projects_model.py
- time_tracker_api/projects/projects_namespace.py
- time_tracker_api/time_entries/custom_modules/utils.py
> feat(projects): :sparkles: add customer name to projects

- .pre-commit-config.yaml
- README.md
> chore(hooks): :mage: add code formatter in commit hook

- commons/data_access_layer/cosmos_db.py
- tests/commons/data_access_layer/cosmos_db_test.py
- tests/conftest.py
- tests/time_tracker_api/time_entries/time_entries_namespace_test.py
- time_tracker_api/projects/custom_modules/utils.py
- time_tracker_api/projects/projects_model.py
- time_tracker_api/time_entries/custom_modules/utils.py
- time_tracker_api/time_entries/time_entries_model.py
- utils/extend_model.py
- utils/worked_time.py
In this PR I include changes that Fixes #147 .  Changes related to this are in utils/extend_model.py  and utils/worked_time.py
Also included a refactor of the parameter peeker in the find_all method of CosmosDBRepository class. This had the purpose to send a validation function from a high level class to a low level class. This function was running logic that would be better understood if applied in the high level class. Also, eventually we would need to run more than one validation function. With the current changes I pretend make this validation functions easy to modify and debug. This has been discussed with @fabidick22 previously and we agreed on it.
Changes related to remove the peeker parameter are in the files cosmos_db.py, time_entries_model.py. Test were updated to meet this …
> Ref/move custom modules to utils folder#147

- commons/data_access_layer/cosmos_db.py
- tests/time_tracker_api/time_entries/time_entries_namespace_test.py
- time_tracker_api/time_entries/time_entries_model.py
> fix(time-entries): :goal_net: stop time-entry if was left running

- .env.template
- requirements/time_tracker_api/prod.txt
- time_tracker_api/time_entries/time_entries_model.py
- time_tracker_api/time_entries/time_entries_namespace.py
- utils/azure_users.py
- utils/extend_model.py
> :boom: Feat/retrieve users info from azure#155

- commons/data_access_layer/database.py
fix: #170 inscrease description size
> fix: #170 inscrease description size

- commons/data_access_layer/cosmos_db.py
- time_tracker_api/time_entries/time_entries_model.py
- utils/extend_model.py
https://github.com/ioet/time-tracker-backend/issues/168
> Include deleted data when entries are queried

- time_tracker_api/time_entries/time_entries_model.py
- time_tracker_api/time_entries/time_entries_namespace.py
New attribute for the number of results to return (`/time-entries?limit=4`)
Resolves #174
> Find last time-entry in project

- time_tracker_api/time_entries/time_entries_model.py
- time_tracker_api/time_entries/time_entries_namespace.py
Reverts ioet/time-tracker-backend#185
> Revert "fix: :goal_net: return 204 when time-entry not found in running"

- commons/data_access_layer/cosmos_db.py
- time_tracker_api/time_entries/time_entries_model.py
> fix: :bug: remove mutable defaults #187

- time_tracker_api/time_entries/time_entries_model.py
- time_tracker_api/time_entries/time_entries_namespace.py
> feat: :construction: add time_offset column #190

- tests/time_tracker_api/time_entries/time_entries_namespace_test.py
- time_tracker_api/time_entries/time_entries_model.py
- time_tracker_api/time_entries/time_entries_namespace.py
- utils/time.py
Close #201 
Fixes https://github.com/ioet/time-tracker-ui/issues/449
Don't merge this PR yet.
> feat: :boom: add timezone_offset in date range filter #201

- README.md
- commons/data_access_layer/cosmos_db.py
- tests/commons/data_access_layer/cosmos_db_test.py
- tests/time_tracker_api/time_entries/time_entries_namespace_test.py
- time_tracker_api/__init__.py
- time_tracker_api/api.py
- time_tracker_api/time_entries/time_entries_model.py
- time_tracker_api/time_entries/time_entries_namespace.py
Updating `/time-entries/paginated` endpoint. 
The requests should look like this: `{{baseUrl}}/time-entries/paginated?start_date=2020-09-10T00:00:00-05:00&end_date=2020-09-10T23:59:59-05:00&user_id=*&timezone_offset=300&start=0&length=2`
And the response is going to be:
```
{
"records_total": 25,
"data": [
{
"running": true,
"owner_id": "fba4417a-8135-42bc-83ab-6e38ba0eb4f9",
"project_name": "My project",
"activity_name": "Development",
"owner_email": "test2@ioet.com",
"customer_id": "dd0efe6a-00ag-4d4f-be70-4858dta61d6a",
"customer_name": "Test customer",
"id": "6b2f2b40-c2e8-483e-bb25-8cfff0a3c30",
"tenant_id": "01c91861-ac36-43f4-9964-17bd525974a4",
"deleted": null,
"project_id": "73d6a125-385a-446e-87e2-16a8ffa5b41b,
"activity_id": "73d6a125-385a-446e-87e2-16a8ffa5b41b", …
```
> feat: Fixing paginated time entries endpoint

- tests/time_tracker_api/users/users_namespace_test.py
- time_tracker_api/users/users_namespace.py
- utils/azure_users.py
> TT - 112 Update role field

- tests/time_tracker_api/time_entries/time_entries_namespace_test.py
- tests/utils/azure_users_test.py
- time_tracker_api/time_entries/time_entries_dao.py
- utils/azure_users.py
Feature to filter time entries report by test and admin roles
> Tt 123 separe test users in report data

- tests/time_tracker_api/users/users_namespace_test.py
- tests/utils/azure_users_test.py
- time_tracker_api/users/users_namespace.py
- utils/azure_users.py
Some functions from `utils/azure_users.py` are also implemented in #252 and the unit tests for those functions are in that PR. 
I would need to rebase after #252 is merged.
> feat: TT-122 show users by type of user

- tests/time_tracker_api/users/users_namespace_test.py
- tests/utils/azure_users_test.py
- time_tracker_api/users/users_namespace.py
- utils/azure_users.py
Endpoint to check if a user is member of a group in azure.
> feat: TT-154 add is user member of a group endpoint

- tests/time_tracker_api/users/users_namespace_test.py
- tests/utils/azure_users_test.py
- time_tracker_api/users/users_namespace.py
- utils/azure_users.py
Change the design of the endpoint is user in a group.
> fix: TT-162 change endpoint is user in group to a post

- .gitignore
- commons/data_access_layer/cosmos_db.py
- tests/commons/data_access_layer/cosmos_db_test.py
- time_tracker_api/time_entries/time_entries_repository.py
Count method was moved from CosmosDBRepository to TimeEntryCosmosDBRepository, the test for that method was removed from tests\commons\data_access_layer\cosmos_db_test.py
> refactor: TT-179 count method moved to TimeEntryCosmosDBRepository

- tests/conftest.py
- tests/time_tracker_api/activities/activities_model_test.py
- tests/utils/repository_test.py
- time_tracker_api/activities/activities_model.py
- utils/repository.py
Create methods find_all_with_id_in_list in ActivityCosmosDBRepository and get_all_with_id_in_list
Implementation of the test methods in activities_model_test.py in tests\time_tracker_api\activities
> Tt 180 create method get activities by id list in activitydao

- requirements/time_tracker_api/prod.txt
- tests/time_tracker_api/time_entries/time_entries_model_test.py
- tests/time_tracker_api/time_entries/time_entries_query_builder_test.py
- tests/utils/query_builder_test.py
- tests/utils/repository_test.py
- time_tracker_api/time_entries/time_entries_query_builder.py
- time_tracker_api/time_entries/time_entries_repository.py
- utils/query_builder.py
- utils/repository.py
**CosmosDBQueryBuilder** and **TimeEntryQueryBuilder** class implementation, 
new function in utils/repository.py called get_string_without_empty_spaces which is used in tests
find_all_v2 in time_entries_repository.py
> Tt 185 find all method in time entries

- tests/time_tracker_api/projects/projects_model_test.py
- time_tracker_api/projects/projects_model.py
create method to get all projects with list of ids
> refactor: TT-182 create method to get all projects with list of ids

- tests/time_tracker_api/time_entries/time_entries_namespace_test.py
- time_tracker_api/api.py
- time_tracker_api/time_entries/time_entries_namespace.py
- time_tracker_api/time_entries/time_entries_repository.py
Handle this error with a message 204
> fix: TT-206 return 404 when a time entry is not running

- tests/time_tracker_api/time_entries/time_entries_model_test.py
- tests/utils/query_builder_test.py
- time_tracker_api/time_entries/time_entries_dao.py
- time_tracker_api/time_entries/time_entries_repository.py
- utils/query_builder.py
Add build query with not in and add id_running_entry in params
> fix: TT-225 Add build query with not in

- tests/time_tracker_api/time_entries/time_entries_namespace_test.py
- time_tracker_api/time_entries/time_entries_dao.py
We fixed the bug that present when the user update Start Time. For this, we added "owner_id" inside the "update" method of the file "time_entries_dao".
> Tt 237 update time entries

- tests/time_tracker_api/projects/projects_model_test.py
- tests/time_tracker_api/projects/projects_namespace_test.py
- time_tracker_api/customers/customers_model.py
- time_tracker_api/projects/projects_model.py
There is an error when trying to consulting to the endpoint:
```bash
<time-tracker-backend-url>/projects/<project-id>
```
The response brings the customer name of the project **null**.
The method **get** on **ProjectCosmosDBDao** class has been modified and add the correct behavior to fix this error.
Also, tests have been added to verify its correct operation.
> fix: TT-257 customer name null on get project by id

- tests/conftest.py
I modified the conftest.py file to save the instance of the TimeEntryCosmosDBRepository object and allow the entry created in the tests to be deleted.
> fix: TT-256 Avoid creating fake users from test

- tests/time_tracker_api/time_entries/time_entries_repository_test.py
- time_tracker_api/time_entries/time_entries_repository.py
handle response Not found, and added unit testing of method add_complementary_info
> fix: TT-261 handle response Not found 

- tests/conftest.py
- tests/time_tracker_api/time_entries/time_entries_model_test.py
- tests/time_tracker_api/time_entries/time_entries_namespace_test.py
- tests/utils/validate_entries_test.py
- time_tracker_api/time_entries/time_entries_namespace.py
- time_tracker_api/time_entries/time_entries_repository.py
- utils/validate_entries.py
Currently, if we want to create a new entry and we don't pass `activity_id` field, the  activity will be create without a problem. 
For example: 
This behavior can cause problems when we try to get all the Entries and in the UI part, it will not render reports Page, and time Entries page.
With  this PR, it is checked that an activity and a project are provided, and also that the projects or activities entered exist. for example:
**Entry without `activity_id` field:**
**Entry with fake `activity_id` field: **
> fix: TT-270 Handle exceptions in create update entries

- tests/conftest.py
- tests/time_tracker_api/time_entries/time_entries_model_test.py
- tests/time_tracker_api/time_entries/time_entries_namespace_test.py
- tests/utils/validate_entries_test.py
- time_tracker_api/time_entries/time_entries_namespace.py
- time_tracker_api/time_entries/time_entries_repository.py
- utils/validate_entries.py
Currently, if we want to create a new entry and we don't pass `activity_id` field, the  activity will be create without a problem. 
For example: 
This behavior can cause problems when we try to get all the Entries and in the UI part, it will not render reports Page, and time Entries page.
With  this PR, it is checked that an activity and a project are provided, and also that the projects or activities entered exist. for example:
**Entry without `activity_id` field:**
**Entry with fake `activity_id` field: **
> fix: TT-270 Fix handle exceptions in create update entries (#301)

- tests/utils/azure_users_test.py
- utils/azure_users.py
Currently the Reports Page does not load the emails of some users, this is because the current implementation does not take into account that the Azure endpoint only returns the first 100 users.
In the user request, if there are more users, the Azure api returns an additional field named `o.datanextLink`, as long as the API returns this field he following number of remaining users is consumed.
> fix: TT-287 Fix users email doesn't show in reports page

- .gitignore
- tests/time_tracker_api/projects/projects_model_test.py
- time_tracker_api/project_types/project_types_model.py
- time_tracker_api/projects/projects_model.py
- time_tracker_api/projects/projects_namespace.py
Currently, when archiving a customer, the columns of projects and customers cannot be displayed in the time entries and report pages.
The code was modified so that when a customer is archived it does not affect the functionality of the time entries and report pages, and the columns with problems can be displayed normally.
> fix: TT-274 fix error on archive a customer removes the project

- requirements/azure_cosmos.txt
- requirements/commons.txt
Currently  we need to upgrade urllib3 to version 1.26.5 or later. Because earlier versions allows CRLF injection if the attacker controls the HTTP request method, The problem is that another package (`request==2.23.0`) needs `urllib3==1.25.8`
The issue has been fixed in urllib3 v1.26.5, so we upgrade urllib3 to that version and we also upgrade request package to `2.25.1`
> fix: TT-302 Fix dependencies vulnerabilities

- README.md
- cosmosdb_emulator/README.md
- requirements/time_tracker_api/dev.txt
- tests/commons/data_access_layer/cosmos_db_test.py
- time-tracker.sh
All the README documentation was updated to support the new way of running the project, in this case, everything was run with docker-compose, also documentation was added for the correct use of the "Time Tracker CLI", in charge of generating data fake in the cosmos emulator.
> docs: TT-301 Update readme documentation and add Time Tracker CLI docs

- commons/data_access_layer/cosmos_db.py
- tests/commons/data_access_layer/cosmos_db_test.py
- tests/time_tracker_api/activities/activities_model_test.py
- tests/time_tracker_api/time_entries/time_entries_namespace_test.py
- tests/time_tracker_api/time_entries/time_entries_query_builder_test.py
- tests/utils/query_builder_test.py
- time_tracker_api/time_entries/time_entries_query_builder.py
- utils/query_builder.py
The function find_all within the CosmosDBRepository contains an earlier implementation, without using the project's query builder
With this PR this implementation is updated, using the query builder, in addition to eliminating implementations that are no longer necessary, since they are implemented at the Query builder level, also some refactoring is done in most of the modified files.
> refactor: TT-245 refactor on find all function in cosmos db repository class

- tests/time_tracker_api/activities/activities_model_test.py
- time_tracker_api/activities/activities_model.py
When we create a new activity, the default active state is not added, which causes errors when presenting in the UI, like this: 
With this PR this behavior is modified and an active status is added by default
> fix: TT-303 Create activity with active status

- .pre-commit-config.yaml
- README.md
- commons/git_hooks/enforce_semantic_commit_msg.py
- In the backend review this file: enforce_semantic_commit_msg.py
- Update the backend with released semantic-release tags that are used in the UI
- Remove the tag style in the BK.
- Add a new tag for Code Smell  Bk
> Tt 305 tags semantic release

- cosmosdb_emulator/time_tracker_cli/providers/common.py
- tests/time_tracker_api/activities/activities_model_test.py
- tests/time_tracker_api/activities/activities_namespace_test.py
- tests/time_tracker_api/customers/customers_namespace_test.py
- tests/time_tracker_api/projects/projects_namespace_test.py
- tests/utils/query_builder_test.py
- time_tracker_api/activities/activities_model.py
- time_tracker_api/activities/activities_namespace.py
- time_tracker_api/customers/customers_model.py
- time_tracker_api/customers/customers_namespace.py
- time_tracker_api/projects/projects_namespace.py
- utils/enums/status.py
- utils/query_builder.py
In many parts of the backend code, variables have been statically defined as 'active'/'inactive', this makes it difficult to maintain the code in the long term, so the use of Enums should be prioritized with this PR this objective was achieved
> refactor: TT-308 Use enums insted defined variables

- tests/time_tracker_api/time_entries/time_entries_repository_test.py
- time_tracker_api/time_entries/time_entries_repository.py
**Problem**
------------
In the time-entries section, when there is no data, the message "The data could not be load" is displayed.
**Solution**
------------
When there is no data, the message "The data could not be load" must not be displayed, instead the message "No data available in table" should be displayed in the table section. That is the purpose of this pull request.
> fix: TT-304 Handle message: the data could not be load

- cosmosdb_emulator/time_tracker_cli/factories/project_factory.py
- cosmosdb_emulator/time_tracker_cli/utils/project.py
- tests/time_tracker_api/projects/projects_model_test.py
- tests/time_tracker_api/projects/projects_namespace_test.py
- tests/time_tracker_api/time_entries/time_entries_dao_test.py
- time_tracker_api/projects/projects_model.py
- time_tracker_api/projects/projects_namespace.py
- time_tracker_api/time_entries/time_entries_dao.py
Currently there is no endpoint that allows to know which are the latest projects in which the user has created entries. This functionality is performed by an external library, which stores the projects in the local storage browser. With this PR this functionality has been created to extract the projects in which the user has generated entries, taking into account the user's last 20 entries.
> feat: TT-326 Get recent projects

- time_tracker_api/activities/activities_model.py
Reverts ioet/time-tracker-backend#348
> Revert "test: TT-384 get all activities from blob storage"

- .github/workflows/python-package.yml
ci: TT-411 inject secrets environment and test_db_connection
> ci: TT-411 inject secrets environment and test_db_connection

- V2/Makefile
PR - Config Makefile for automate tests
Execute 'make'
```
---------------HELP-----------------
To install the dependencies type make install
To test the project type make test
To run the local database type make start-local
To run all comands type make ci
------------------------------------
```
> feat: TT-399 Config use makefile to executing tests

- V2/README.md
Readme update for how to use makefile.
> docs: TT-399 Readme update how to use makefile

- .github/workflows/time-tracker-v1-on-push-workflow.yml
Since our Azure DevOps pipeline has no more minutes remaining to be run, we have the need to have a new way to run the continuous integration process. That way is using GitHub Actions and this PR is to add the workflow to run some steps when code is pushed to master. It should build an image and push to ACR.
An important change is related how the image is tagged, now it will tagged with git hash.
> ci: [TT-412] adds ci workflow when push to master

- V2/README.md
Add information about the project like:
- Stack technologies
- Installation environment
- Start project
- How to contribute to the project
> docs: update readme V2

- V2/serverless.yml
- V2/tests/api/azure/time_entry_azure_endpoints_test.py
- V2/tests/integration/daos/time_entries_dao_test.py
- V2/tests/unit/services/time_entry_service_test.py
- V2/tests/unit/use_cases/time_entries_use_case_test.py
- V2/time_tracker/time_entries/_application/__init__.py
- V2/time_tracker/time_entries/_application/_time_entries/__init__.py
- V2/time_tracker/time_entries/_application/_time_entries/_get_time_entries.py
- V2/time_tracker/time_entries/_domain/__init__.py
- V2/time_tracker/time_entries/_domain/_persistence_contracts/_time_entries_dao.py
- V2/time_tracker/time_entries/_domain/_services/_time_entry.py
- V2/time_tracker/time_entries/_domain/_use_cases/__init__.py
- V2/time_tracker/time_entries/_domain/_use_cases/_get_time_entry_by_id_use_case.py
- V2/time_tracker/time_entries/_domain/_use_cases/_get_time_entry_use_case.py
- V2/time_tracker/time_entries/_infrastructure/_data_persistence/__init__.py
- V2/time_tracker/time_entries/_infrastructure/_data_persistence/_time_entries_sql_dao.py
- V2/time_tracker/time_entries/interface.py
In this pull request, the functionality  to GET  all time_entries and get specific time_entry by id 
To learn more about the Time Tracker project architecture, you can access it [here](https://github.com/eguezgustavo/time_tracker_app_skeleton).
> feat: TT-404 get v2 time entries.

- V2/time_tracker/utils/enums/__init__.py
- V2/time_tracker/utils/enums/response_enums.py
enums were created so that they can be used in the reply messages, these messages were added
````
INVALID_ID = "Invalid Format ID"
NOT_FOUND = "Not found"
NOT_CREATED = "could not be created"
INCORRECT_BODY = "Incorrect body"
MIME_TYPE = "application/json"
````
> feat: TT-429 created enums for response messages

- V2/serverless.yml
- V2/tests/api/azure/time_entry_azure_endpoints_test.py
- V2/tests/integration/daos/time_entries_dao_test.py
- V2/tests/unit/services/time_entry_service_test.py
- V2/tests/unit/use_cases/time_entries_use_case_test.py
- V2/time_tracker/time_entries/_application/__init__.py
- V2/time_tracker/time_entries/_application/_time_entries/__init__.py
- V2/time_tracker/time_entries/_application/_time_entries/_get_latest_entries.py
- V2/time_tracker/time_entries/_domain/__init__.py
- V2/time_tracker/time_entries/_domain/_persistence_contracts/_time_entries_dao.py
- V2/time_tracker/time_entries/_domain/_services/_time_entry.py
- V2/time_tracker/time_entries/_domain/_use_cases/__init__.py
- V2/time_tracker/time_entries/_domain/_use_cases/_get_latest_entries_use_case.py
- V2/time_tracker/time_entries/_infrastructure/_data_persistence/_time_entries_sql_dao.py
- V2/time_tracker/time_entries/interface.py
This pull request get the n (20 default) latest entries from an user
> feat:TT-407 list latest v2 time entries

- .github/workflows/time-tracker-v1-on-pull-request-workflow.yml
- .github/workflows/time-tracker-v1-on-push-workflow.yml
add new enviroments to CI github actions
> ci: TT-384 add new secret ci

- .github/workflows/time-tracker-v1-on-pull-request-workflow.yml
- requirements/time_tracker_api/prod.txt
- tests/commons/data_access_layer/file_stream_test.py
- tests/utils/azure_users_test.py
- utils/azure_users.py
* Fix get all users from AD.
* Fix dependencies errors.
* Fix tests due to changes in the code.
> Fix: All ioet users are returned from AD
